# Generated by Django 5.0.14 on 2026-06-18 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='courses.subject'),
        ),
        migrations.AddField(
            model_name='qrsession',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_sessions', to='courses.subject'),
        ),
        migrations.AddField(
            model_name='qrsession',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_sessions', to='teachers.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'subject', 'date')},
        ),
    ]
